tacoday-api:
    image: jgilli/tacoday-api
    expose:
        - "8080"
    environment:
        FB_APP_TARGET_PAGE:
        FB_APP_TOKEN:

taco-slackbot:
    image: jgilli/taco-slackbot
    links:
        - tacoday-api
    environment:
        SLACK_TOKEN:
